/**
 * Authoritative error registry (data only).
 * Codes and Arabic/English messages transcribed from:
 *   RULE_*  → 04_RULE_ENGINE_REVISED §14
 *   PROMPT_* → 06_PROMPT_ENGINE §21
 *   COVER_*  → 08_COVER_ENGINE §19
 *   EXPORT_* → 09_EXPORT_ENGINE §19
 * No engine logic. This is a catalog.
 */
import {
  EngineId,
  RuleDomain,
  RulePriorityClass,
  ValidationCheck,
  ValidationSeverity,
} from '../domain-model';
import type { ErrorEntry, ErrorNamespace } from './types';

const B = ValidationSeverity.Blocking;
const W = ValidationSeverity.Warning;

function entry(
  code: string,
  namespace: ErrorNamespace,
  originEngine: EngineId,
  severity: ValidationSeverity,
  check: ValidationCheck | null,
  priorityClass: RulePriorityClass | null,
  domain: RuleDomain | null,
  messageAr: string,
  messageEn: string,
): ErrorEntry {
  return {
    code,
    namespace,
    originEngine,
    severity,
    check,
    priorityClass,
    domain,
    messageAr,
    messageEn,
  };
}

const RULE_ENTRIES: readonly ErrorEntry[] = [
  entry(
    'RULE_PA_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'منطقة الطباعة محجوبة بأيدٍ فوقها؛ يجب أن تبقى واضحة.',
    'Print area obstructed by hands.',
  ),
  entry(
    'RULE_PA_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'منطقة الطباعة محجوبة بالشعر؛ يجب أن تبقى واضحة.',
    'Print area obstructed by hair.',
  ),
  entry(
    'RULE_PA_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'عناصر (إكسسوارات) تغطي منطقة الطباعة؛ غير مسموح.',
    'Props overlap the print area.',
  ),
  entry(
    'RULE_PA_004',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'ثنيات عميقة تشوّه منطقة الطباعة؛ غير مسموح.',
    'Deep folds distort the print area.',
  ),
  entry(
    'RULE_PA_005',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'ظلال تغطي منطقة الطباعة؛ غير مسموح.',
    'Shadows cover the print area.',
  ),
  entry(
    'RULE_PA_005N',
    'RULE',
    EngineId.Validation,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'نسبة الظل فوق منطقة الطباعة تتجاوز الحد المسموح.',
    'Shadow coverage exceeds the profile limit.',
  ),
  entry(
    'RULE_PA_006',
    'RULE',
    EngineId.Validation,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'منطقة الطباعة أصغر من الحد الأدنى المطلوب.',
    'Print area below minSizeRatio.',
  ),
  entry(
    'RULE_PA_007',
    'RULE',
    EngineId.Validation,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.PrintArea,
    'منطقة الطباعة غير متمركزة ضمن الحد المسموح.',
    'Print area off-center beyond tolerance.',
  ),
  entry(
    'RULE_TXT_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.Background,
    'يوجد نص مقروء في الخلفية؛ غير مسموح في صور المنتج.',
    'Readable background text detected.',
  ),
  entry(
    'RULE_CLG_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.Output,
    'المخرج الفردي عبارة عن كولاج؛ يجب أن يكون صورة منتج واحدة متماسكة.',
    'Individual output is a collage.',
  ),
  entry(
    'RULE_CLG_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.PrintRules,
    RulePriorityClass.PrintArea,
    RuleDomain.Output,
    'صورة البيع (A) تحتوي على تصميم/شعار/علامة مائية/نص؛ يجب أن تكون فارغة.',
    'Sale Image (A) is not blank.',
  ),
  entry(
    'RULE_AUD_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Audience,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Model,
    'لا يُسمح بعارضين بالغين مع جمهور الأطفال.',
    'Adult models forbidden for Kids audience.',
  ),
  entry(
    'RULE_AUD_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Audience,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Model,
    'لا يُسمح بعارضين بالغين مع منتجات الأطفال.',
    'Adult models forbidden for Kids products.',
  ),
  entry(
    'RULE_AUD_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Audience,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Session,
    'نوع الجمهور غير محدد أو غير صالح.',
    'Audience missing or invalid.',
  ),
  entry(
    'RULE_AUD_004',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Audience,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Model,
    'لا يُسمح بعارضين أطفال مع جمهور البالغين.',
    'Child models forbidden for adult audiences.',
  ),
  entry(
    'RULE_PRD_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Product,
    'هذا المنتج مخصص للأطفال فقط ويجب اختيار جمهور الأطفال.',
    'Kids-only product requires Kids audience.',
  ),
  entry(
    'RULE_PRD_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Product,
    'الجمهور المختار غير مسموح لهذا المنتج.',
    'Selected audience not allowed for product.',
  ),
  entry(
    'RULE_PRD_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Product,
    'زاوية العرض غير مدعومة لهذا المنتج.',
    'View not supported by product.',
  ),
  entry(
    'RULE_PRD_004',
    'RULE',
    EngineId.Rule,
    W,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Product,
    'مساحة الطباعة لهذا المنتج قريبة من الحد الأدنى.',
    'Product print zone near minimum.',
  ),
  entry(
    'RULE_SEA_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Season,
    RulePriorityClass.Season,
    RuleDomain.Decor,
    'لا يُسمح بديكور عيد الأم في جلسة عيد الأب.',
    "Mother's-Day decor forbidden on Father's Day.",
  ),
  entry(
    'RULE_SEA_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Season,
    RulePriorityClass.Season,
    RuleDomain.Decor,
    'لا يُسمح بمشاهد (الأم والطفل) في جلسة عيد الأب.',
    "Mother/Child hero forbidden on Father's Day.",
  ),
  entry(
    'RULE_SEA_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Season,
    RulePriorityClass.Season,
    RuleDomain.Decor,
    'لا يُسمح بديكور من موسم آخر داخل هذا الموسم.',
    'Foreign-season decor forbidden.',
  ),
  entry(
    'RULE_SEA_004',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Season,
    RulePriorityClass.Season,
    RuleDomain.Decor,
    'وضع الاستوديو البسيط لا يسمح بأي ديكور موسمي.',
    'Minimal Studio forbids seasonal decor.',
  ),
  entry(
    'RULE_SEA_005',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Season,
    RulePriorityClass.Season,
    RuleDomain.Validation,
    'الموسم غير محدد أو غير صالح.',
    'Season missing or invalid.',
  ),
  entry(
    'RULE_PAL_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Colors,
    RulePriorityClass.PaletteLock,
    RuleDomain.GarmentColor,
    'لون القطعة خارج الألوان المقفلة المختارة.',
    'Garment color outside the locked selection.',
  ),
  entry(
    'RULE_PAL_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Colors,
    RulePriorityClass.PaletteLock,
    RuleDomain.GarmentColor,
    'لون المشهد خارج مجموعة الألوان المختارة.',
    'Scene garment color not in selected set.',
  ),
  entry(
    'RULE_PAL_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Colors,
    RulePriorityClass.PaletteLock,
    RuleDomain.Palette,
    'لم يتم اختيار أي لون.',
    'No color selected.',
  ),
  entry(
    'RULE_DUP_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.DuplicateScenes,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Composition,
    'يوجد مشهد مكرر (نفس المشهد والوضعية وزاوية الكاميرا والتكوين).',
    'Duplicate scene signature.',
  ),
  entry(
    'RULE_CNT_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.SceneCount,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Composition,
    'عدد المشاهد الفريدة الممكنة أقل من العدد المطلوب.',
    'Unique space < requested count.',
  ),
  entry(
    'RULE_CNT_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.SceneCount,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Composition,
    'عدد المشاهد المطلوب يجب أن يكون واحدًا على الأقل.',
    'Requested count must be ≥ 1.',
  ),
  entry(
    'RULE_PRV_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Output,
    'صورة المعاينة تتطلب صورة PNG مرفوعة.',
    'Preview requires uploaded PNG.',
  ),
  entry(
    'RULE_PRV_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Output,
    'يجب أن تعتمد صورة المعاينة على صورة البيع (A).',
    'Preview must derive from Output A.',
  ),
  entry(
    'RULE_PRV_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Output,
    'صورة المعاينة قديمة؛ تم تعديل صورة البيع المصدر.',
    'Preview stale; source A changed.',
  ),
  entry(
    'RULE_COV_001',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.CoverData,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Cover,
    'الغلاف يستخدم صور البيع (A) فقط ولا يستخدم صور المعاينة (B).',
    'Cover must use Sale Images (A) only.',
  ),
  entry(
    'RULE_COV_002',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.CoverData,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Cover,
    'لا يمكن إنشاء الغلاف قبل اكتمال جميع صور البيع (A).',
    'Cover blocked until all A ready.',
  ),
  entry(
    'RULE_COV_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.CoverData,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Cover,
    'تخطيط الغلاف لا يطابق عدد الموك أب.',
    'Cover layout ≠ mockup count.',
  ),
  entry(
    'RULE_ART_001',
    'RULE',
    EngineId.Rule,
    W,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Artwork,
    'ملف التصميم لا يحتوي على شفافية (Alpha).',
    'Artwork lacks transparency.',
  ),
  entry(
    'RULE_ART_002',
    'RULE',
    EngineId.Rule,
    W,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Artwork,
    'نسبة أبعاد التصميم لا تطابق منطقة الطباعة.',
    'Artwork aspect mismatch.',
  ),
  entry(
    'RULE_ART_003',
    'RULE',
    EngineId.Rule,
    B,
    ValidationCheck.Products,
    RulePriorityClass.SceneAesthetic,
    RuleDomain.Artwork,
    'صيغة الملف غير مدعومة؛ يجب أن تكون PNG.',
    'Unsupported format; PNG required.',
  ),
  entry(
    'RULE_CFG_001',
    'RULE',
    EngineId.Rule,
    B,
    null,
    null,
    null,
    'خطأ في إعداد القواعد؛ شرط أو مُعامل غير صالح.',
    'Invalid condition/operator shape.',
  ),
  entry(
    'RULE_CFG_002',
    'RULE',
    EngineId.Rule,
    B,
    null,
    null,
    null,
    'مرجع سياق غير صالح في تأثير القاعدة.',
    'Invalid ContextRef in effect.',
  ),
  entry(
    'RULE_CFG_003',
    'RULE',
    EngineId.Rule,
    B,
    null,
    null,
    RuleDomain.GarmentColor,
    'قاعدة موسم تستهدف لون القطعة؛ غير مسموح.',
    'Season rule targets garment color (forbidden).',
  ),
];

const PROMPT_ENTRIES: readonly ErrorEntry[] = [
  entry(
    'PROMPT_SRC_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Output,
    'لا يمكن تنفيذ صورة المعاينة: صورة البيع (A) المصدر غير مرفقة.',
    'Output B blocked: source Sale Image (A) not attached.',
  ),
  entry(
    'PROMPT_PNG_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Output,
    'لا يمكن تنفيذ صورة المعاينة: ملف التصميم PNG غير مرفوع.',
    'Output B blocked: PNG artwork missing.',
  ),
  entry(
    'PROMPT_STALE_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Output,
    'صورة المعاينة قديمة؛ يجب إعادة توليدها من صورة البيع المحدثة.',
    'Output B stale; regenerate from updated A.',
  ),
  entry(
    'PROMPT_PRD_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Product,
    'المنتج غير صالح أو غير معروف.',
    'Invalid product.',
  ),
  entry(
    'PROMPT_VIEW_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Product,
    'زاوية العرض غير مدعومة لهذا المنتج.',
    'View not supported by product.',
  ),
  entry(
    'PROMPT_COLOR_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    RulePriorityClass.PaletteLock,
    RuleDomain.GarmentColor,
    'لون القطعة خارج الألوان المختارة.',
    'Garment color outside selection.',
  ),
  entry(
    'PROMPT_COLLAGE_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    RulePriorityClass.PrintArea,
    RuleDomain.Output,
    'طلب يولّد كولاج/عدة صور؛ غير مسموح — صورة واحدة لكل طلب.',
    'Collage/multi-image request; one image per prompt only.',
  ),
  entry(
    'PROMPT_ART_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Artwork,
    'محاولة اختراع/إعادة رسم التصميم؛ يُسمح فقط باستخدام ملف PNG المرفوع.',
    'Artwork invention/redraw attempt; only the uploaded PNG is allowed.',
  ),
  entry(
    'PROMPT_COV_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Cover,
    'الغلاف يستخدم صور البيع (A) فقط ولا يستخدم صور المعاينة (B).',
    'Cover must use Sale Images (A) only.',
  ),
  entry(
    'PROMPT_VAR_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Prompt,
    'متغيّر غير محلول في القالب.',
    'Unresolved prompt variable.',
  ),
  entry(
    'PROMPT_MOD_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    null,
    RuleDomain.Prompt,
    'إصدار وحدة برومبت غير صالح أو غير متوافق.',
    'Invalid module version.',
  ),
  entry(
    'PROMPT_AUD_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    RulePriorityClass.AudienceSafety,
    RuleDomain.Model,
    'لا يُسمح للبالغين بارتداء منتجات الأطفال.',
    'Adults may not wear Kids products.',
  ),
  entry(
    'PROMPT_TXT_001',
    'PROMPT',
    EngineId.Prompt,
    B,
    null,
    RulePriorityClass.PrintArea,
    RuleDomain.Background,
    'لا يُسمح بنص مقروء داخل المشهد.',
    'Readable scene text not allowed.',
  ),
];

const COVER_ENTRIES: readonly ErrorEntry[] = [
  entry(
    'COVER_BARRIER_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'لا يمكن إنشاء الغلاف قبل اكتمال جميع صور البيع (A).',
    'Cover blocked until all Sale Images (A) are ready.',
  ),
  entry(
    'COVER_SRC_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'الغلاف يستخدم صور البيع (A) فقط ولا يستخدم صور المعاينة (B).',
    'Cover must use Sale Images (A) only, never Previews (B).',
  ),
  entry(
    'COVER_LOCK_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'ممنوع تعديل أو إعادة توليد أي صورة مصدر في الغلاف.',
    'Altering/regenerating any source image is forbidden.',
  ),
  entry(
    'COVER_DUP_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'توجد صورة بيع مكررة في الغلاف.',
    'Duplicate Sale Image in the cover.',
  ),
  entry(
    'COVER_COUNT_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'عدد الموك أب لا يطابق عدد صور البيع.',
    'Mockup count mismatches Sale Image count.',
  ),
  entry(
    'COVER_COLOR_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.Colors,
    RulePriorityClass.PaletteLock,
    RuleDomain.GarmentColor,
    'يوجد لون في شريط الألوان خارج الألوان المقفلة.',
    'Strip color outside the locked selection.',
  ),
  entry(
    'COVER_META_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'بيانات الغلاف ناقصة.',
    'Missing cover metadata.',
  ),
  entry(
    'COVER_LAYOUT_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'تخطيط الغلاف لا يطابق عدد الموك أب.',
    'Cover layout does not match mockup count.',
  ),
  entry(
    'COVER_GREENBG_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'خلفية خضراء غير مسموحة افتراضيًا؛ استخدم خلفية محايدة دافئة.',
    'Green background not allowed by default; use warm neutral.',
  ),
  entry(
    'COVER_VAR_001',
    'COVER',
    EngineId.Cover,
    B,
    ValidationCheck.CoverData,
    null,
    RuleDomain.Cover,
    'متغيّر غير محلول في قالب الغلاف.',
    'Unresolved variable in cover template.',
  ),
];

const EXPORT_ENTRIES: readonly ErrorEntry[] = [
  entry(
    'EXPORT_CLIP_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'تعذّر الوصول إلى الحافظة.',
    'Clipboard unavailable.',
  ),
  entry(
    'EXPORT_CLIP_002',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'تم رفض إذن الحافظة؛ استخدم تنزيل TXT كبديل.',
    'Clipboard denied; use TXT fallback.',
  ),
  entry(
    'EXPORT_FILE_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'تعذّر إنشاء الملف.',
    'File creation failed.',
  ),
  entry(
    'EXPORT_ZIP_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'تعذّر إنشاء حزمة ZIP.',
    'ZIP creation failed.',
  ),
  entry(
    'EXPORT_SCOPE_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'نطاق التصدير غير صالح.',
    'Invalid export scope.',
  ),
  entry(
    'EXPORT_SCOPE_002',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'لا يوجد محتوى ضمن النطاق المحدد.',
    'Empty export scope.',
  ),
  entry(
    'EXPORT_MISSINGA_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Output,
    'برومبت صورة البيع (A) مفقود.',
    'Missing Output A prompt.',
  ),
  entry(
    'EXPORT_LINK_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Output,
    'ارتباط A/B مكسور.',
    'Broken A/B linkage.',
  ),
  entry(
    'EXPORT_PNG_001',
    'EXPORT',
    EngineId.Export,
    W,
    null,
    null,
    RuleDomain.Artwork,
    'بيانات التصميم PNG مفقودة.',
    'Missing artwork metadata.',
  ),
  entry(
    'EXPORT_STALE_001',
    'EXPORT',
    EngineId.Export,
    W,
    null,
    null,
    RuleDomain.Output,
    'صورة المعاينة قديمة.',
    'Stale preview.',
  ),
  entry(
    'EXPORT_COVER_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Cover,
    'الغلاف يستخدم صور البيع (A) فقط.',
    'Cover must use Output A only.',
  ),
  entry(
    'EXPORT_COVERCOUNT_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Cover,
    'عدد صور الغلاف غير صحيح.',
    'Wrong cover count.',
  ),
  entry(
    'EXPORT_FILENAME_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'اسم ملف غير صالح.',
    'Invalid filename.',
  ),
  entry(
    'EXPORT_PATH_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'مسار الملف طويل جدًا.',
    'Path too long.',
  ),
  entry(
    'EXPORT_CHECKSUM_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'فشل التحقق من المجموع (SHA-256).',
    'Checksum failure.',
  ),
  entry(
    'EXPORT_CORRUPT_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'نسخة احتياطية/مشروع تالف.',
    'Corrupted backup/project.',
  ),
  entry(
    'EXPORT_SCHEMA_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'إصدار المخطط غير مدعوم.',
    'Unsupported schema version.',
  ),
  entry(
    'EXPORT_RESTORE_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'تعارض في الاستعادة؛ يلزم التأكيد.',
    'Restore conflict; confirmation required.',
  ),
  entry(
    'EXPORT_RESTORE_002',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'نسخة أحدث من التطبيق؛ لا يمكن الاستعادة.',
    'Backup newer than app; cannot restore.',
  ),
  entry(
    'EXPORT_STORAGE_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'مساحة التخزين غير كافية.',
    'Insufficient storage.',
  ),
  entry(
    'EXPORT_CANCELLED_001',
    'EXPORT',
    EngineId.Export,
    W,
    null,
    null,
    RuleDomain.Export,
    'تم إلغاء التصدير.',
    'Export cancelled.',
  ),
  entry(
    'EXPORT_PROMPTVAR_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Prompt,
    'متغيّر غير محلول في البرومبت.',
    'Unresolved prompt variable.',
  ),
  entry(
    'EXPORT_NUM_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Export,
    'ترقيم غير صالح.',
    'Invalid numbering.',
  ),
  entry(
    'EXPORT_GROUP_001',
    'EXPORT',
    EngineId.Export,
    B,
    null,
    null,
    RuleDomain.Group,
    'عضوية مجموعة غير صالحة.',
    'Invalid group membership.',
  ),
];

/** The full, ordered error catalog (data only). */
export const ERROR_REGISTRY: readonly ErrorEntry[] = [
  ...RULE_ENTRIES,
  ...PROMPT_ENTRIES,
  ...COVER_ENTRIES,
  ...EXPORT_ENTRIES,
];

/** Frozen lookup map, keyed by error code (built once, pure data transform). */
export const ERROR_BY_CODE: Readonly<Record<string, ErrorEntry>> = Object.freeze(
  ERROR_REGISTRY.reduce<Record<string, ErrorEntry>>((acc, e) => {
    acc[e.code] = e;
    return acc;
  }, {}),
);
